### ISSUE TITLE
Installation fails due to missing bower resolution

### ISSUE THREAD

**Issue by carloschida** [sealuzh/PerformanceHat#2]
With a fresh clone of the current version, when executing `mvn install` in `cw-feedback-eclipse-parent` the following error occurs:
`
[INFO] --- frontend-maven-plugin:0.0.23:bower (bower install) @ cw-feedback-handler ---
[INFO] Running 'bower install' in /Users/carloschida/Apps/PerformanceHat/cw-feedback-handler
[ERROR] [{
[ERROR]   "level": "info",
[ERROR]   "id": "not-cached",
...
[ERROR]   "id": "ENOTFOUND",
[ERROR]   "level": "error",
[ERROR]   "message": "Package @1.4.0 not found",
[ERROR]   "stacktrace": "Error: Package @1.4.0 not found\n    at createError (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/util/createError.js:4:15)\n    at /Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/core/resolverFactory.js:206:23\n    at _fulfilled (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:796:13)\n    at /Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:604:44\n    at runSingle (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:137:13)\n    at flush (/Users/carloschida/Apps/PerformanceHat/cw-feedback-handler/node_modules/bower/lib/node_modules/q/q.js:125:13)\n    at process._tickCallback (node.js:355:11)"
[ERROR] }]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PerformanceHat Parent Project ...................... SUCCESS [  0.185 s]
[INFO] PerformanceHat Feedback Shared Library ............. SUCCESS [  2.045 s]
[INFO] PerformanceHat Monitoring .......................... SUCCESS [  1.147 s]
[INFO] PerformanceHat Dependencies Module ................. SUCCESS [  9.825 s]
[INFO] PerformanceHat Build Module ........................ SUCCESS [  0.031 s]
[INFO] PerformanceHat Base Module ......................... SUCCESS [  1.579 s]
[INFO] PerformanceHat Performance Eclipse-Plugin .......... SUCCESS [  0.220 s]
[INFO] PerformanceHat Costs Eclipse-Plugin ................ SUCCESS [  0.130 s]
[INFO] PerformanceHat Feature Module ...................... SUCCESS [  0.127 s]
[INFO] PerformanceHat P2UpdateSite Module ................. SUCCESS [  1.659 s]
[INFO] PerformanceHat Target Module ....................... SUCCESS [  0.010 s]
[INFO] FDD Feedback Handler ............................... FAILURE [  6.300 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.215 s
[INFO] Finished at: 2016-08-25T21:50:17+02:00
[INFO] Final Memory: 51M/681M
[INFO] ------------------------------------------------------------------------
`

The error is due to the inability of bower to select the correct version of angular in `cw-feedback-handler`. Thus I tried `bower install` in that directory which replies with:

```
Unable to find a suitable version for angular, please choose one:
    1) angular#1.4.12 which resolved to 1.4.12 and is required by angular-animate#1.4.12, angular-cookies#1.4.12, angular-resource#1.4.12
    2) angular#~1.4.0 which resolved to 1.4.12 and is required by eu.cloudwave.wp5.feedbackhandler.webapp
    3) angular#1.5.8 which resolved to 1.5.8 and is required by angular-animate#1.5.8, angular-aria#1.5.8
    4) angular#^1.0.8 which resolved to 1.5.8 and is required by angular-ui-router#0.2.18
    5) angular#>=1.0.4 which resolved to 1.5.8 and is required by ng-clip#0.2.6
    6) angular#^1.3.0 || >1.4.0-beta.0 which resolved to 1.5.8 and is required by angular-material#0.9.8

Prefix the choice with ! to persist it to bower.json

? Answer 
```

By using the answer `!2`, the resolution is stored by adding the following lines to `bower.json`: 

```
"resolutions": {
    "angular": "~1.4.0"
  }
```

There doesn't seem to be unit tests for this module, but it's relatively safe to assume that the resolution is enough. Working on a pull request to solve the issue.

**Comment by carloschida** [comment]
See pull request #3.
